<a href="https://colab.research.google.com/github/Balaram-DataScientist/OU-BE-VI-DLT-LAB/blob/Lab-2/OU_DLT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NGIT/KMEC-OU-DLT-2**
**Create Tensors and apply split & merge operations and statistics operations.**

# 1.Merge
Merging means combining multiple tensors into one tensor in a certain
dimension.
Tensors can be merged using concatenate and stack operations.
The concatenate operation does not generate new dimensions. It only merges along existing dimensions.
The stack operation creates new
dimensions.
Whether to use the concatenate or stack operation to merge tensors depends on whether a new dimension needs to be created for a
specific scene.

In [ ]:
# Import tf
import tensorflow as tf

In [ ]:
a = tf.random.normal([4,35,8]) # Create gradebook A
b = tf.random.normal([6,35,8]) # Create gradebook B
tf.concat([a,b],axis=0) # Merge gradebooks

<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[-0.17101863,  1.1268151 ,  1.7628744 , ..., -0.10566344,
          0.35977906, -0.16374265],
        [ 0.0677992 , -0.93658024,  0.5716777 , ..., -0.27536815,
         -0.5093024 , -0.04396725],
        [-0.64013886, -1.149742  , -0.45845297, ...,  0.8298333 ,
         -0.6015075 , -0.31426555],
        ...,
        [ 1.2347813 , -0.30119038, -0.14815825, ..., -0.9715035 ,
         -1.9045607 ,  0.49585733],
        [ 0.87437654,  0.02307163, -0.9613074 , ..., -0.22243258,
          1.4038947 , -0.7224149 ],
        [-0.13757649,  1.005808  ,  0.9333088 , ..., -1.7076746 ,
          2.3764594 ,  2.2321935 ]],

       [[ 0.3703695 , -0.6041486 , -0.63724685, ..., -0.10083157,
         -0.6101804 , -1.4380965 ],
        [-0.4665223 , -1.5220218 ,  1.8318435 , ..., -1.4935918 ,
          0.583802  , -0.30964717],
        [ 1.1924293 ,  0.12707506,  1.6488715 , ...,  0.7810127 ,
         -0.34211284, -0.37883884],
        ...,
 

# a.Concatenation

In [ ]:
# Illegal merge.
a = tf.random.normal([4,32,8])
b = tf.random.normal([6,35,8])
tf.concat([a,b],axis=0)   # Illegal merge. Second dimension is different.

InvalidArgumentError: {{function_node __wrapped__ConcatV2_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ConcatOp : Dimension 1 in both shapes must be equal: shape[0] = [4,32,8] vs. shape[1] = [6,35,8] [Op:ConcatV2] name: concat

In [ ]:
a = tf.random.normal([10,35,4])
b = tf.random.normal([10,35,4])
tf.concat([a,b],axis=2) # Merge along the last dimension

<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[ 8.28447282e-01, -1.70393616e-01, -1.10621619e+00, ...,
         -2.19023913e-01, -1.69349849e-01,  5.62509418e-01],
        [-1.60387993e+00, -7.94826150e-01,  5.61811030e-01, ...,
         -1.82879031e-01,  1.08235967e+00, -1.15403426e+00],
        [-4.88020867e-01,  1.16176009e+00, -1.15319228e+00, ...,
          6.29249513e-01,  1.58969253e-01,  5.51809192e-01],
        ...,
        [-7.31892943e-01,  5.50036967e-01,  1.98541507e-01, ...,
          2.80511200e-01,  7.70564079e-01,  1.55602241e+00],
        [-1.06463358e-01, -8.85586202e-01, -1.27612638e+00, ...,
          8.55016038e-02, -5.26814818e-01,  3.50928813e-01],
        [-2.48936176e+00, -4.12627339e-01, -2.49504566e+00, ...,
         -1.17319949e-01,  7.04458356e-01,  2.80572385e-01]],

       [[-6.51990294e-01, -1.53385139e+00, -3.90938073e-01, ...,
         -1.20407236e+00,  1.39185143e+00, -3.77740443e-01],
        [-2.13056803e-01, -1.17793635e-01,  2.0338

In [ ]:
a = tf.random.normal([35,8])
b = tf.random.normal([35,8])
tf.concat([a,b],axis=0) # No class dimension

<tf.Tensor: shape=(70, 8), dtype=float32, numpy=
array([[-0.17181222, -0.9870395 , -0.806695  , -1.3779808 ,  0.15003695,
        -0.9635736 ,  1.0366856 , -0.16975683],
       [-1.4486609 ,  0.20007041, -2.3188264 ,  0.6357894 , -0.8026352 ,
         0.29125398, -0.07118358,  0.57144266],
       [ 1.5741514 ,  0.9507494 ,  1.3997196 , -0.438675  , -1.115767  ,
         0.6948911 , -0.2880105 ,  0.11782306],
       [ 0.9921358 ,  0.2201967 , -0.45141166, -1.4171374 , -1.9125296 ,
         1.0229497 ,  0.9569838 ,  1.4939449 ],
       [-1.1673214 , -0.02457626, -0.6891068 , -0.618304  ,  0.23080951,
        -1.06048   ,  1.1854954 , -0.7133738 ],
       [ 1.6326573 , -0.8542637 , -0.83066165, -1.1727209 ,  0.3881234 ,
        -0.01483777, -0.5286811 ,  1.1895957 ],
       [-0.87370753, -0.02679097,  0.42572466,  0.9074397 , -1.2891018 ,
         0.822094  , -0.8593132 , -0.01405124],
       [-1.993612  ,  0.31801653,  0.7028661 , -0.46522868, -0.4005237 ,
         0.5599576 ,  0.8162519

# b.Stack

In [ ]:
a = tf.random.normal([35,8])
b = tf.random.normal([35,8])
tf.stack([a,b],axis=0) # Stack a and b and insert new dimension


<tf.Tensor: shape=(2, 35, 8), dtype=float32, numpy=
array([[[ 4.59011048e-01, -8.65595877e-01, -5.30453205e-01,
         -6.52945280e-01,  5.50388873e-01,  8.23858142e-01,
         -4.39046174e-01, -1.87579677e-01],
        [ 6.60735309e-01, -6.88208103e-01, -7.66832352e-01,
          2.19576880e-02,  1.67712522e+00,  1.06480885e+00,
          6.35176659e-01,  1.36851871e+00],
        [-8.59637678e-01, -1.12911654e+00, -1.04430497e-01,
         -3.66145596e-02,  5.93194008e-01,  1.01010896e-01,
          1.08985335e-01,  3.59444141e-01],
        [-6.12147570e-01, -8.54969680e-01,  6.48902357e-01,
          1.07129991e+00,  2.80775249e-01,  2.58396566e-01,
          7.93648362e-01, -1.12083793e+00],
        [ 2.07564041e-01,  3.07162464e-01,  7.64728487e-01,
          1.46822262e+00,  2.18489146e+00,  3.21820349e-01,
          8.05852175e-01, -1.70756292e+00],
        [-7.63774514e-01,  8.80628169e-01, -1.42660093e+00,
          5.84060311e-01, -1.11070955e+00,  1.43075120e+00,
        

In [ ]:
a = tf.random.normal([35,8])
b = tf.random.normal([35,8])
tf.stack([a,b],axis=-1) # Insert new dimension at the end

<tf.Tensor: shape=(35, 8, 2), dtype=float32, numpy=
array([[[-1.76576447e+00, -2.57814169e-01],
        [-1.41065693e+00, -7.68030286e-01],
        [ 4.30037111e-01,  2.38979369e-01],
        [ 9.19530094e-01,  1.66715658e+00],
        [ 8.71081412e-01,  1.68033314e+00],
        [ 9.87689793e-01, -1.06458001e-01],
        [ 1.36257422e+00,  9.54712406e-02],
        [-2.81849146e-01, -7.78393567e-01]],

       [[-3.85659695e-01,  4.83345658e-01],
        [-5.18769622e-01,  4.61868972e-01],
        [-1.47873890e+00,  1.58572781e+00],
        [-1.85086858e+00, -1.35413945e+00],
        [ 1.53665411e+00, -1.55398619e+00],
        [-9.69290376e-01, -1.09315813e+00],
        [ 6.34553254e-01, -1.80184162e+00],
        [-4.17054862e-01,  6.24712348e-01]],

       [[-3.16548571e-02, -1.43041480e+00],
        [-5.94109535e-01,  1.38193524e+00],
        [-1.88821986e-01,  1.99073005e+00],
        [-5.36652021e-02, -8.89804721e-01],
        [ 5.54645360e-01,  8.74555334e-02],
        [ 1.69508144

In [ ]:
# Illegal
a = tf.random.normal([35,4])
b = tf.random.normal([35,8])
tf.stack([a,b],axis=-1) # Illegal use of stack function.

InvalidArgumentError: {{function_node __wrapped__Pack_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Shapes of all inputs must match: values[0].shape = [35,4] != values[1].shape = [35,8] [Op:Pack] name: stack

# 2.Split
The inverse process of the merge operation is split, which splits a tensor
into multiple tensors.

In [ ]:
x = tf.random.normal([10,35,8])
# Cut into 10 pieces with equal length
result = tf.split(x, num_or_size_splits=10, axis=0)
result

[<tf.Tensor: shape=(1, 35, 8), dtype=float32, numpy=
 array([[[ 0.580507  , -0.6791252 , -1.1741041 ,  0.5186085 ,
           0.30274078,  1.1907889 , -1.1838825 , -0.08861321],
         [-0.6281094 ,  1.3605818 ,  1.1656833 , -0.43972096,
           0.64665437, -1.1757123 ,  0.9326842 ,  1.2867385 ],
         [-1.7238977 , -0.5909957 ,  0.44984877,  0.53752154,
          -0.52121073, -0.10207281, -0.7124886 , -0.732401  ],
         [ 1.4743369 , -0.52059054,  0.32128787,  0.0633137 ,
           0.91893023,  0.18212906, -0.1593944 , -0.11935653],
         [ 1.4518331 , -1.0335726 ,  1.6829934 ,  0.5659375 ,
          -0.36717755,  0.16838892, -1.0643874 , -0.3194539 ],
         [-1.2473824 ,  0.92034274, -1.9268361 ,  1.4744787 ,
          -0.75864124, -0.5861636 ,  1.9225408 ,  1.720374  ],
         [-0.18991508, -1.7036091 ,  1.0503776 ,  1.3594438 ,
          -1.0672309 , -1.2073038 , -1.1096188 ,  0.18749721],
         [ 0.7466768 , -0.21748087, -1.4138901 , -1.1934128 ,
          

In [ ]:
len(result) # Return a list with 10 tensors of equal length

10

In [ ]:
result[0]

<tf.Tensor: shape=(1, 35, 8), dtype=float32, numpy=
array([[[ 0.580507  , -0.6791252 , -1.1741041 ,  0.5186085 ,
          0.30274078,  1.1907889 , -1.1838825 , -0.08861321],
        [-0.6281094 ,  1.3605818 ,  1.1656833 , -0.43972096,
          0.64665437, -1.1757123 ,  0.9326842 ,  1.2867385 ],
        [-1.7238977 , -0.5909957 ,  0.44984877,  0.53752154,
         -0.52121073, -0.10207281, -0.7124886 , -0.732401  ],
        [ 1.4743369 , -0.52059054,  0.32128787,  0.0633137 ,
          0.91893023,  0.18212906, -0.1593944 , -0.11935653],
        [ 1.4518331 , -1.0335726 ,  1.6829934 ,  0.5659375 ,
         -0.36717755,  0.16838892, -1.0643874 , -0.3194539 ],
        [-1.2473824 ,  0.92034274, -1.9268361 ,  1.4744787 ,
         -0.75864124, -0.5861636 ,  1.9225408 ,  1.720374  ],
        [-0.18991508, -1.7036091 ,  1.0503776 ,  1.3594438 ,
         -1.0672309 , -1.2073038 , -1.1096188 ,  0.18749721],
        [ 0.7466768 , -0.21748087, -1.4138901 , -1.1934128 ,
          0.78281504,  0.3

In [ ]:
x = tf.random.normal([10,35,8]) # Split tensor into 4 parts
result = tf.split(x, num_or_size_splits=[4,2,2,2] ,axis=0)
len(result)

4

In [ ]:
"""to divide one certain dimension by a length
of 1, we can use the tf.unstack(x, axis) function. This method is a special
case of tf.split. The splitting length is fixed as 1."""
x = tf.random.normal([10,35,8])
result = tf.unstack(x,axis=0)
len(result) # Return a list with 10 tensors


10

# 3. Statistics
In neural network  various statistical attributes need to be computed, such as maximum, minimum, mean, and norm.
Because tensors usually contain a lot of data, it is easier to infer the distribution of
tensor values by obtaining the statistical information of these tensors.

# a.Norm
Norm is a measure of the “length” of a vector. It can be generalized to
tensors.
there 3 types of Norms
L1 Norm ,L2 Norm and infinite Norm

In [ ]:
x = tf.ones([2,2])
tf.norm(x,ord=1) # L1 norm

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

In [ ]:
tf.norm(x,ord=2) # L2 norm

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [ ]:
import numpy as np
tf.norm(x,ord=np.inf) # ∞ norm

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

# b.Max, Min, Mean, and Sum

In [ ]:
#the maximum, minimum, mean, and sum of tensors in a certain dimension or in all dimensions.
x = tf.random.normal([4,10])
x

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[-1.6319009 , -0.88727957, -0.07646927, -0.77202463, -1.3091004 ,
        -1.6873609 , -0.46706423, -0.67094743,  0.9317845 , -3.2593005 ],
       [ 0.23678523,  0.5101082 , -0.43908024,  1.20038   ,  2.228871  ,
         0.44704098, -0.23665497,  0.05624067, -0.27768263, -0.7039925 ],
       [-1.235653  , -1.253041  ,  2.5628371 ,  0.31985363, -1.010094  ,
        -2.1008673 , -2.3111715 ,  0.49769545, -0.41857332,  1.1705279 ],
       [-0.59027463, -0.80483484, -0.21348427,  0.14868473,  0.62433994,
        -0.4419663 ,  0.56609726, -0.5089444 , -1.1203898 ,  0.52750677]],
      dtype=float32)>

In [ ]:
tf.reduce_max(x,axis=1) # get maximum value at 2nd dimension

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.9317845 , 2.228871  , 2.5628371 , 0.62433994], dtype=float32)>

In [ ]:
tf.reduce_min(x,axis=1) # get the minimum value at 2nd dimension

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.2593005, -0.7039925, -2.3111715, -1.1203898], dtype=float32)>

In [ ]:
# Find the mean probabilities of each sample:
tf.reduce_mean(x,axis=1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.9829664 ,  0.30220157, -0.37784863, -0.18132655], dtype=float32)>

In [ ]:
x = tf.random.normal([4,10])
x

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[-0.797909  , -1.6324226 ,  0.33498728,  1.9541718 ,  1.722752  ,
        -2.0044312 , -0.2566551 , -0.48571143,  0.8431844 ,  1.0528709 ],
       [-0.62068444,  0.7776948 , -0.10645437,  0.26149783, -1.1826487 ,
        -0.12689263,  1.5766089 , -0.64023113,  0.47982854, -0.28012493],
       [-0.05803626,  0.5078634 ,  0.9694931 , -1.0115465 , -0.44392687,
         0.7083824 ,  0.8130356 , -0.95905834, -0.91733766, -0.92528456],
       [ 1.5721836 , -0.7639095 , -1.9252135 , -1.1514283 ,  0.7144405 ,
         0.94210607,  0.18525812, -0.61121505, -2.7051349 ,  1.3811477 ]],
      dtype=float32)>

In [ ]:
tf.reduce_max(x),tf.reduce_min(x),tf.reduce_mean(x)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.9541718>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-2.7051349>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-0.07021876>)

# c. Error Function

In [ ]:
""" error function is the  error of each sample can be obtained through
the MSE function, and the average error of the sample  """
out = tf.random.normal([4,10]) # Simulate output
print("out=",out)

y = tf.constant([1,2,2,0]) # Real labels
print("\n 1. y with real labels=",y)
y = tf.one_hot(y,depth=10) # One-hot encoding
print("\n 2. y with one hot encoding=",y)
loss = tf.keras.losses.mse(y,out) # Calculate loss of each sample
print("\n 3. mse loss =",loss)
loss = tf.reduce_mean(loss) # Calculate mean loss
print("\n 4. reduced mean loss=",loss)


out= tf.Tensor(
[[ 0.72704273  1.0351005   0.9047861  -0.11060961 -1.6913927  -0.73392856
   1.7299687  -1.6391189  -1.6480584  -0.06465402]
 [-2.3196974  -0.03333734 -1.2224005  -0.745023    1.2775669   1.2325059
   1.7867059   0.47058797  1.4838097   0.2388656 ]
 [-0.45600668  0.7426074   0.538234    1.2613431   1.8569134  -0.24234559
  -3.1633024   0.33296725 -1.1778996   0.41596475]
 [-0.5317638   0.75084203  0.5556559   0.28788143 -1.5193325   0.09175223
   0.3702613  -1.1981668  -0.60289156  0.1622877 ]], shape=(4, 10), dtype=float32)

 1. y with real labels= tf.Tensor([1 2 2 0], shape=(4,), dtype=int32)

 2. y with one hot encoding= tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)

 3. mse loss = tf.Tensor([1.3159935  1.9699997  1.7748306  0.75809956], shape=(4,), dtype=float32)

 4. reduced mean loss= tf.Tensor(1.4547307, shape=(), dtype=float32)
