<a href="https://colab.research.google.com/github/Balaram-DataScientist/OU-BE-VI-DLT-LAB/blob/Lab-1/OU_DLT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NGIT/KMEC-OU-DLT-1**
**Create Tensors  and perform basic operations with tensors**

In [ ]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution is: {}".format(tf.executing_eagerly()))        # https://www.tensorflow.org/guide/eager
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.17.0
Eager execution is: True
Keras version: 3.4.1


checking wether GPU is available or not

In [ ]:
var = tf.Variable([3, 3])

if tf.test.is_gpu_available():
    print('Running on GPU')
    print('GPU #0?')
    print(var.device.endswith('GPU:0'))
else:
    print('Running on CPU')

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


Running on CPU


In [ ]:
import tensorflow as tf

const = tf.constant(24)
print(const)

tf.Tensor(24, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf

f1 = tf.Variable(54.0)
print(f1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=54.0>


varaibles in Tensorflow

In [ ]:
#default int type is tf.int32, float is tf.float32
t0 = 24                # python variable
t1 = tf.Variable(42)   # tensor variable
t2 = tf.Variable(89.)  # tensor variable
t4 = tf.Variable([[1,2],[3,4]])
t3 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(t0)
print(t1)
print(t2)
print(t3)
print(t4)

24
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>


In [ ]:
t = tf.Variable([1,2,3,4])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
t = tf.Variable([1,2],[3,4])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
f1 = tf.Variable(54.)
f1.assign(38.)     #This operation outputs a Tensor that holds the new value of ref after the value has been assigned.
print(f1)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=38.0>


In [ ]:
d = tf.Variable(12, dtype = tf.float64) #change default data type
print(d.dtype)

<dtype: 'float64'>


In [ ]:
#constants
con=tf.constant(24)
print(con)
#print(con.dtype)
con.numpy() #converting tensor into numpy variable

tf.Tensor(24, shape=(), dtype=int32)


24

In [ ]:
d1=tf.constant(1, dtype = tf.int64)
print(d1)

tf.Tensor(1, shape=(), dtype=int64)


rank (dimensions) of a tensor

In [ ]:
print(tf.rank(t3))
#The rank of a tensor is the number of indices required to uniquely select each element of the tensor.
# Rank is also known as "order", "degree", or "ndims."
print(tf.rank(t3).numpy())

tf.Tensor(3, shape=(), dtype=int32)
3


Reshape tensor

In [ ]:
t2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) # tensor variable
print(t2.shape)

(2, 2, 3)


In [ ]:
a1 = tf.reshape(t2,[2,6]) # 2 rows 6 cols
#reshape method in tensor
a2 = tf.reshape(t2,[1,12]) # 1 rows 12 cols

In [ ]:
print(a1)
print(a2)

tf.Tensor(
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]], shape=(2, 6), dtype=float32)
tf.Tensor([[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]], shape=(1, 12), dtype=float32)


find size of tensor

In [ ]:
s = tf.size(input=a2).numpy()
#number of elements in tensor
print(s)

12


In [ ]:
#arithematic operations
import tensorflow as tf
#arithmetic operations
print(tf.add(4,5))
print(tf.add([1,2],[3,4]))
print(tf.square(9))
print(tf.reduce_sum([[6,4,4],[3,2,1],[8,1,2]]))#what is reduce_sum?
print(tf.square(4)+tf.square(6))

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(81, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(52, shape=(), dtype=int32)


Casting tensor to numpy variable

In [ ]:
print(t2.numpy())
print(t2[1, 0, 2].numpy())   # slice 1, row 0, column 2
#accessing elements from tensor
print(t2.dtype)   #data type of a tensor

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]
8.0
<dtype: 'float32'>



element wise multiplication with overloaded operator


In [ ]:
print(t2*t2)

tf.Tensor(
[[[  0.   1.   4.]
  [  9.  16.  25.]]

 [[ 36.  49.  64.]
  [ 81. 100. 121.]]], shape=(2, 2, 3), dtype=float32)


In [ ]:
#Tensorflow variables broadcasting
b1 = t2*3
print(b1)

tf.Tensor(
[[[ 0.  3.  6.]
  [ 9. 12. 15.]]

 [[18. 21. 24.]
  [27. 30. 33.]]], shape=(2, 2, 3), dtype=float32)


transpose of a matrix and matrix multiplication

In [ ]:
x = tf.constant([[2,4,3]])
y = tf.constant([[1,2,3]])
print(x)
print(y)
z=tf.transpose(y)
print(z)
mul=tf.matmul(x,z)
print(mul)

tf.Tensor([[2 4 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
tf.Tensor([[19]], shape=(1, 1), dtype=int32)


Casting a tensor to another datatype

In [ ]:
print(x)

tf.Tensor([[2 4 3]], shape=(1, 3), dtype=int32)


In [ ]:
 c= tf.cast(x, dtype=tf.float32)
 print(c)

tf.Tensor([[2. 4. 3.]], shape=(1, 3), dtype=float32)


In [ ]:
#adding tensors
i=tf.Variable(12)
j=tf.Variable(27)
print(tf.add(i,j))

tf.Tensor(39, shape=(), dtype=int32)


Ragged Tensors

In [ ]:
ragged =tf.ragged.constant([[1, 2, 6, 5], [], [7, 10, 8], [4], [9,7]])

print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[1, 2, 6, 5], [], [7, 10, 8], [4], [9, 7]]>
tf.Tensor([1 2 6 5], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 7 10  8], shape=(3,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)
tf.Tensor([9 7], shape=(2,), dtype=int32)


In [ ]:
print(tf.RaggedTensor.from_row_splits(values=[5, 2, 6, 1, 4, 10, 7, 8, 6, 7],row_splits=[0, 4, 4, 7, 8, 10]))

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>


useful TensorFlow functions

In [ ]:
x = [1,3,5,7,11]
y = 5
s = tf.math.squared_difference( x,  y) #() x-y)*(x-y) with broadcasting
print(s)

tf.Tensor([16  4  0  4 36], shape=(5,), dtype=int32)


In [ ]:
#mean
numbers = tf.constant([[3., 4.], [6., 9.]])
print(tf.reduce_mean(input_tensor=numbers))

tf.Tensor(5.5, shape=(), dtype=float32)


In [ ]:
print(tf.reduce_mean(input_tensor=numbers, axis=0)) #Find mean across columns
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True)

tf.Tensor([4.5 6.5], shape=(2,), dtype=float32)


<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 6.5]], dtype=float32)>

In [ ]:
#Find mean across rows
print(tf.reduce_mean(input_tensor=numbers, axis=1))
tf.reduce_mean(input_tensor=numbers, axis=1, keepdims=True)

tf.Tensor([3.5 7.5], shape=(2,), dtype=float32)


<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[3.5],
       [7.5]], dtype=float32)>

Output a tensor of the given shape filled with values from a normal distribution.

In [ ]:
r=tf.random.normal(shape = (3,2), mean=10, stddev=2, dtype=tf.float32, seed=None,  name=None) #Outputs random values from a normal distribution
print(r)

tf.Tensor(
[[ 6.2103586  8.879451 ]
 [ 5.517803   8.184371 ]
 [12.425876  10.774782 ]], shape=(3, 2), dtype=float32)


In [ ]:
u=tf.random.uniform(shape = (2,4),  minval=0, maxval=None, dtype=tf.float32, seed=None,  name=None)
#Outputs random values from a uniform distribution
print(u)

tf.Tensor(
[[0.3241868  0.4402815  0.7927984  0.7863594 ]
 [0.01648772 0.6073545  0.4948573  0.12172747]], shape=(2, 4), dtype=float32)
